### ISSUE TITLE
fmmpeg not being recognised (macOS) 

### ISSUE THREAD

**Issue by Hardfg5000** [glisco03/isometric-renders#75] opened 2023-08-10 13:34 UTC
Hello, I've been trying to get the animation options working in the mod but for some reason, ffmpeg is not being detected. I have tried installing it via brew.sh and also manually putting the ffmpeg folder and file in the .minecraft folder but nothing worked still. Is there anything I'm missing? I am using an M1 chip if that matters and using PrismLauncher.

**Comment by gliscowo** [comment] 2023-08-19 21:43
As you can see in [this comment](https://github.com/gliscowo/isometric-renders/issues/46#issuecomment-1401333511) on issue #46, it is not currently possible to use FFmpeg on macOS without modifying your launcher settings

Since this also a duplicate of the mentioned issue, I'll be closing it
Cheers

**Closed as not planned by gliscowo** 2023-08-19 21:43 UTC
